### ISSUE TITLE
the size of the test dataset

### ISSUE THREAD

**Issue by nancy-ux** [hwayoon2/UGPNet#4]
Hi, I appreciate your work very much! 
However, I am wondering why the size of the test dataset is 3,000 in the paper. I find that the size of the test dataset(CelebA-HQ) is 30,000. Is that a clerical error? If it's not, it will be great to know how to pick the 3,000 images.

**Comment by hwayoon2** [comment]
Hello, thank you for reaching out. We utilized the first 3,000 images from CelebA-HQ for our test set.
